### ISSUE TITLE
command failed on unraid 6.10 rc3, error gathering device information while adding custom device "/dev/dri": no such file or directory

### ISSUE THREAD

**Issue by kjames2001** [linuxserver/docker-kdenlive#3]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Install kdenlive from CA in unraid

## Current Behavior

docker: Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.

## Steps to Reproduce

1.installed kdenlive from community apps in unraid 6.10 rc3
2.changed the port only
3.got this error: docker: Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.

## Environment
**OS: unraid**
**CPU architecture:** arm64
**How docker service was installed: CA**

## Command used to create docker container (run/create/compose/screenshot)

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='kdenlive' --net='bridge' -e TZ="Africa/Gaborone" -e HOST_OS="Unraid" -e HOST_HOSTNAME="James-Cloud" -e HOST_CONTAINERNAME="kdenlive" -e 'SUBFOLDER'='/' -e 'KEYBOARD'='en-us-qwerty' -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='022' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:3000]' -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/kdenlive-logo.png' -p '3033:3000/tcp' -v '/mnt/user/appdata/kdenlive':'/config':'rw' --device='/dev/dri' 'lscr.io/linuxserver/kdenlive'
b4566fbc8a1b031a1ea6bffa33c58e239923f1232019ce97227d317c0abd1ccb
docker: Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.

The command failed.

## Docker logs

no logs

**Comment by Roxedus** [comment]
Remove the device from the template.
