### ISSUE TITLE
unable to start latest version kdenlive after successsfully install from CA in unraid 6.10 rc3

### ISSUE THREAD

**Issue by kjames2001** [linuxserver/docker-kdenlive#4]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

kdenlive should be up and running

## Steps to Reproduce

1.installed kdenlive from unraid 6.10 rc3 CA
2.removed /dev/dri as previously reported and instructed.
3.get connection refused when trying to access webui
4.

## Environment
**OS: unraid**
**CPU architecture:** arm64
**How docker service was installed:**

from unraid CA

## Command used to create docker container (run/create/compose/screenshot)

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='kdenlive' --net='bridge' -e TZ="Africa/Gaborone" -e HOST_OS="Unraid" -e HOST_HOSTNAME="James-Cloud" -e HOST_CONTAINERNAME="kdenlive" -e 'SUBFOLDER'='/' -e 'KEYBOARD'='en-us-qwerty' -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='022' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:3000]' -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/kdenlive-logo.png' -p '3033:3000/tcp' -v '/mnt/user/appdata/kdenlive':'/config':'rw' 'lscr.io/linuxserver/kdenlive'
12f043b69387a7273cb29a70af469b49aacef581a3d6b93b4aa3d07834f3331b

The command finished successfully!

## Docker logs

today at 08:12:14 1: 0xb09980 node::Abort() [node]
today at 08:12:14 2: 0xb099fe  [node]
today at 08:12:14 3: 0xb78e9e  [node]
today at 08:12:14 4: 0xb78f66 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node]
today at 08:12:14 5: 0xaccf49 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [node]
today at 08:12:14 6: 0xacd1f9 node::Start(int, char**) [node]
today at 08:12:14 7: 0x14ed2a0e0d90  [/lib/x86_64-linux-gnu/libc.so.6]
today at 08:12:14 8: 0x14ed2a0e0e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
today at 08:12:14 9: 0xa400ec  [node]
today at 08:12:15node[543]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

**Comment by kjames2001** [comment]
same issue seems to affect webtop from CA too.

**Comment by thelamer** [comment]
Ubuntu-kde webtop and this image are based on Jammy. You likely need to pass `--security-opt seccomp=unconfined` to the image to work on older hosts. I don't know much about Unraid, but I know we have other images with GPU support so their must be some kind of system of installing host level drivers to have a /dev/dri device. 
Please let me know if that works for you.

**Comment by kjames2001** [comment]
Added --security-opt seccomp=unconfined to extra parameters, now both containers work!

Thanks a ton!

Dont know what changed in 6.10 rc3, but this wasnt required in 6.10 rc2.
